SCTO_user     = "xxxx@equilibriumbdc.com"
SCTO_password = "password1234"
SCTO_server   = "ffff"

gd_token   = "qwerty1234"
gd_rtoken  = "asdfg09876"
gd_cid     = "4iop.apps.googleusercontent.com"
gd_csecret = "ABCDEF"

aai_key = "juliuscaesar"
OPENAI_API_KEY = "sk-goettingen"

wa_token = "berlin-city"
wa_phone = "112233445566"